#!/bin/sh

echo "Running scalafmt check..."

git diff --quiet && git diff --cached --quiet
HAS_CHANGES=$?  # 0 = no changes, 1 = changes

if [ $HAS_CHANGES -ne 0 ]; then
  git stash
fi

sbt scalafmtCheckAll
if [ $? -ne 0 ]; then
  echo "scalafmt check failed. Please run 'sbt scalafmtAll' to format your code before pushing."

  if [ $HAS_CHANGES -ne 0 ]; then
    git stash pop
  fi
  exit 1
fi

if [ $HAS_CHANGES -ne 0 ]; then
  git stash pop
fi
exit 0
